//! Decay sweep for recomputable derivations (§11.5, settled 2026-08-13).
//!
//! The Verifier can prove mechanically that a computed belief no longer
//! holds — `verify::rederive_npmi` recomputes the statistic from the
//! current `mention` table. This module decides what to *do* about that.
//!
//! Four doctrinal points, each of which changes the code:
//!
//! 1. **Decay closes valid time, not system time.** The pattern was real
//!    when derived; the world moved. So [`fact::close_valid_time`], not
//!    `supersede_fact` — `facts_as_of` must keep answering correctly for
//!    the period the belief held.
//! 2. **Decay calibrates, it does not demote.** D3 demotes a class on
//!    in-use *correction*, because a correction indicts the producer.
//!    Decay indicts nobody: the linker was right. A high decay rate says
//!    the class's threshold or λ is mis-tuned — a tuning signal, kept in
//!    a separate channel from trust so the ladder stays meaningful.
//! 3. **An input-set collapse is a bug report, not a decay event.** A
//!    pair going from 297 shared episodes to zero did not drift apart;
//!    its mentions were destroyed (alias-mention rebuild, node merge).
//!    Auto-closing there would delete a well-founded belief over an
//!    unrelated pipeline artifact, so that shape raises an integrity
//!    alarm and touches nothing. Genuine decay looks the opposite way:
//!    the statistic falls while the input count holds or GROWS.
//! 4. **Statements track their arithmetic.** A co-occurrence statement
//!    embeds its numbers, and that text is FTS-indexed and embedded — a
//!    frozen "NPMI 0.82" on a pair now at 0.35 means retrieval serves
//!    arithmetic the graph no longer believes. Drift re-renders the text
//!    (and drops the stale vector so the nightly re-embeds it).
//!
//! Automation is safe here because of the guards, not because a human
//! glances at it: hysteresis below a second band (no flapping), a cap
//! per run, and a veto for anything a human personally verified. A queue
//! of hundreds of "co-occurrence decayed" cards would be exactly the
//! O(facts) oversight D1 exists to eliminate.

use rusqlite::{params, Connection, OptionalExtension};
use serde::Serialize;

use crate::error::Result;
use crate::fact;
use crate::linkers::NPMI_THRESHOLD;

/// Close only well below threshold. Without a band, a pair hovering at
/// the boundary closes and re-asserts nightly — and since `assert_fact`
/// only corroborates *live* facts, each re-assertion would mint a new
/// row, accumulating flap history forever. Same two-band shape as
/// precheck's dup/flag thresholds.
pub const DECAY_FLOOR_RATIO: f64 = 0.8;
/// Per-run close cap (cf. `AA_MAX_CANDIDATES`, `RULE_CAP`). A backlog
/// drains over successive nightlies, visibly.
pub const DECAY_CAP: usize = 40;
/// An input set losing this fraction of its episodes is a pipeline
/// signal, not drift.
pub const COLLAPSE_RATIO: f64 = 0.5;

pub fn decay_floor() -> f64 {
    NPMI_THRESHOLD * DECAY_FLOOR_RATIO
}

#[derive(Debug, Default, Serialize)]
pub struct DecayReport {
    pub scanned: usize,
    /// Qualified for closing (below the floor). Reported even when the
    /// cap stopped us — no silent truncation.
    pub eligible: usize,
    pub closed: usize,
    /// Statements re-rendered because their numbers drifted.
    pub refreshed: usize,
    /// Below threshold but inside the hysteresis band — left live.
    pub held_band: usize,
    /// Human-verified: recomputation never overrides a person.
    pub held_user: usize,
    /// Input-set collapses seen for the FIRST time, or that got worse since
    /// they were last seen: `(statement, detail)`. Data-integrity alarms.
    ///
    /// New and worsened only, on purpose. This list ran at 44-56 entries
    /// every night for eighteen days without one night differing from the
    /// last, because the check had no memory — and an alarm that repeats
    /// identically forever is one a reader learns to skip, which is the
    /// state a real collapse would have to arrive into. See
    /// `migrations::V024_COOCCURRENCE_ALARM` for what the counts turned out
    /// to track.
    pub integrity_alarms: Vec<(String, String)>,
    /// Collapses already reported and no worse than when they were first
    /// seen. A number, not a list: they are still true and still unresolved,
    /// and dropping them entirely would be the opposite error.
    pub integrity_alarms_continuing: usize,
    /// Unparseable statements — left alone rather than guessed at.
    pub unparsed: usize,
}

/// Parse the numbers a co-occurrence statement carries:
/// `"… frequently co-occur (5 shared episodes, NPMI 0.53)"` → `(5, 0.53)`.
/// The format is generated by `link_npmi` and re-rendered by
/// [`render_statement`], so it stays under our control — but a parse
/// failure is treated as "unknown", never as zero.
pub fn parse_cooccurrence(statement: &str) -> Option<(i64, f64)> {
    let open = statement.rfind('(')?;
    let close = statement.rfind(')')?;
    if close <= open {
        return None;
    }
    let (left, right) = statement[open + 1..close].split_once(", NPMI ")?;
    let co = left.split_whitespace().next()?.parse().ok()?;
    let npmi = right.trim().parse().ok()?;
    Some((co, npmi))
}

/// Re-render a co-occurrence statement with current numbers, preserving
/// the entity-naming prefix.
pub fn render_statement(statement: &str, co: i64, npmi: f64) -> Option<String> {
    let open = statement.rfind('(')?;
    Some(format!(
        "{}({co} shared episodes, NPMI {npmi:.2})",
        &statement[..open]
    ))
}

/// Sweep live co-occurrence facts: re-derive each, close the decayed,
/// refresh drifted numbers, alarm on input collapse.
pub fn sweep_npmi(conn: &Connection, dry_run: bool) -> Result<DecayReport> {
    let mut rep = DecayReport::default();
    let rows: Vec<(i64, String, String, String, String)> = {
        let mut stmt = conn.prepare(
            "SELECT id, uid, subject_id, object_id, statement FROM fact
             WHERE extractor = 'npmi' AND object_id IS NOT NULL
               AND polarity = 'positive'
               AND valid_to IS NULL AND invalidated_at IS NULL",
        )?;
        let rows = stmt
            .query_map([], |r| {
                Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?))
            })?
            .collect::<std::result::Result<_, _>>()?;
        rows
    };

    for (id, uid, a, b, statement) in rows {
        rep.scanned += 1;
        let Some((stated_co, stated_npmi)) = parse_cooccurrence(&statement) else {
            rep.unparsed += 1;
            continue;
        };
        let current = crate::verify::rederive_npmi(conn, &a, &b)?;

        // The true count, independent of whether NPMI can be *computed* from
        // it. `rederive_npmi` answers None for three different reasons — a
        // corpus under 10 episodes, a co-occurrence under NPMI_MIN_COOCCUR,
        // or a node with no episodes at all — and only the last is an empty
        // input set. Reading None as zero conflated "below the floor" with
        // "gone", which is how this alarm came to print `→ 0 shared episodes`
        // for a pair that still shared two, and then blame the mention
        // pipeline for it. Measured 2026-08-15: of 53 alarms surviving a
        // phantom repair, the repair itself found zero beliefs without
        // support — the whole gap was this conflation.
        let now_co = crate::linkers::shared_episodes(conn, &a, &b)?.len() as i64;

        // (3) Input-set collapse ⇒ pipeline bug, hands off the belief.
        //
        // Collapse is judged on the count, never on None. A pair that fell to
        // one or two shared episodes has NOT lost its mentions — it has drifted
        // below the floor NPMI needs, which is ordinary decay and belongs to
        // the branch below, not to an alarm telling the operator to go and
        // debug ingestion.
        let collapsed = (now_co as f64) < (stated_co as f64) * COLLAPSE_RATIO;
        if collapsed {
            // Loud only when it is news. `prior` is what this belief's
            // collapse looked like the last time it was reported; a
            // collapse that has not deepened since then is counted and not
            // re-narrated.
            // `first_observed_co` as well as the latest: the message says
            // "when first reported", and the upsert overwrites `observed_co`
            // on every non-dry run — so a pair eroding 50 → 40 → 30 across
            // three nights reported "(was 40 when first reported)" on the
            // third. The first number was unrecoverable from the row.
            let prior: Option<(i64, i64, i64)> = conn
                .query_row(
                    "SELECT stated_co, observed_co, \
                            COALESCE(first_observed_co, observed_co) \
                     FROM cooccurrence_alarm WHERE fact_uid = ?1",
                    rusqlite::params![uid],
                    |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
                )
                .optional()?;
            let news = match prior {
                None => true,
                // **Both halves of the remembered row, not just the
                // observation.** `stated_co` is parsed out of the statement
                // prose, and the `refreshed` path below re-renders that
                // prose when the numbers drift — so a belief can collapse,
                // recover, be re-rendered against a higher baseline, and
                // collapse again from it. Comparing observations alone
                // called that "continuing": remembered 3, restated to 100,
                // today 20 — an 80-episode loss reported as nothing,
                // because 20 < 3 is false. A moved baseline means the
                // remembered observation is not comparable, so it is news.
                Some((before_stated, before_observed, _)) => {
                    now_co < before_observed || stated_co != before_stated
                }
            };
            // **Gated on `dry_run` like every other write in this sweep.**
            // Ungated it was worse than a false "nothing changed": a dry run
            // CONSUMED the news. An operator previewing tonight's collapses
            // recorded them, and the real run that followed reported
            // `new=0` — downgrading a first sighting to a silent
            // "continuing" number that no later run would ever raise again.
            // The exact suppression this branch exists to prevent, reachable
            // through the command that promises to change nothing.
            if !dry_run {
                conn.execute(
                    "INSERT INTO cooccurrence_alarm
                         (fact_uid, stated_co, observed_co, first_observed_co)
                     VALUES (?1, ?2, ?3, ?3)
                     ON CONFLICT(fact_uid) DO UPDATE SET
                         observed_co = excluded.observed_co,
                         stated_co = excluded.stated_co,
                         -- Backfill, or V025 never reaches the rows it was
                         -- written for: a V024-era row has NULL here, and a
                         -- persistently-collapsed pair never hits the reap,
                         -- so it is never re-INSERTed and stays NULL for the
                         -- life of the belief. The COALESCE in the reader
                         -- would then resolve the first sighting to last
                         -- night, on precisely the rows that motivated V025.
                         first_observed_co =
                             COALESCE(first_observed_co, excluded.observed_co),
                         last_seen_at = datetime('now')",
                    rusqlite::params![uid, stated_co, now_co],
                )?;
            }
            if news {
                let how = match prior {
                    None => String::new(),
                    // The FIRST observation, which is what the sentence
                    // claims. Naming the previous sweep's number instead
                    // also narrated a "worsening" for a pair that had
                    // partially recovered since its first sighting.
                    Some((_, _, first)) => format!(" (was {first} when first reported)"),
                };
                rep.integrity_alarms.push((
                    statement.chars().take(90).collect(),
                    format!(
                        "input set {stated_co} → {now_co} shared episodes{how}: the stated \
                         count is what this belief was minted with, and a merge, split or \
                         relink moves episodes between nodes by design — so check whether \
                         either node was re-partitioned before suspecting the mention \
                         pipeline. Belief left untouched either way."
                    ),
                ));
            } else {
                rep.integrity_alarms_continuing += 1;
            }
            continue;
        }

        // **Not collapsed: reap the row.** Without this the table means
        // "was collapsed once", not "is collapsed" — and the consequence is
        // not just tidiness. A pair that recovers to exactly its stated
        // count does not trip the refresh, so the baseline never moves, and
        // an undone-then-redone re-partition files a genuinely fresh
        // collapse as "already reported and no worse since". Deleting on
        // the healthy path also reaps rows for facts this sweep later
        // closes.
        if !dry_run {
            conn.execute(
                "DELETE FROM cooccurrence_alarm WHERE fact_uid = ?1",
                rusqlite::params![uid],
            )?;
        }

        // Not collapsed, but NPMI may still be uncomputable — a pair that
        // slid just under NPMI_MIN_COOCCUR without crossing the collapse
        // ratio lands exactly here. That used to be impossible, because
        // `collapsed` swallowed every None; now that collapse is judged on
        // the count, this case is real and must not `expect`.
        //
        // It is ordinary decay, so it takes the ordinary decay path: below
        // the floor the linker itself requires, the belief no longer has the
        // support that produced it. Valid-time close — true then, false now,
        // nobody was wrong — and it respects the same user-verified hold and
        // per-run cap as every other close, because a pair sliding from 3
        // shared episodes to 2 is exactly what this sweep is for.
        let Some((npmi, co)) = current else {
            if fact::is_user_verified(conn, id)? {
                rep.held_user += 1;
                continue;
            }
            rep.eligible += 1;
            if rep.closed >= DECAY_CAP || dry_run {
                continue;
            }
            fact::close_valid_time(conn, &uid, None)?;
            let payload = serde_json::json!({
                "class": "npmi", "reason": "below_npmi_min_cooccur",
                "shared_was": stated_co, "shared_now": now_co,
                "npmi_min_cooccur": crate::linkers::NPMI_MIN_COOCCUR,
            });
            crate::ledger::log_event(
                conn,
                "belief_decayed",
                Some(&uid),
                Some(&payload.to_string()),
            )?;
            rep.closed += 1;
            continue;
        };

        // (4) Numbers drifted ⇒ re-render, whatever the verdict.
        if (npmi - stated_npmi).abs() > 0.01 || co != stated_co {
            if let Some(fresh) = render_statement(&statement, co, npmi) {
                if !dry_run {
                    conn.execute(
                        "UPDATE fact SET statement = ?2 WHERE id = ?1",
                        params![id, fresh],
                    )?;
                    // The old vector describes text that no longer exists;
                    // dropping it re-queues the fact for `pkg embed`.
                    conn.execute("DELETE FROM vec_fact WHERE fact_id = ?1", params![id])?;
                }
                rep.refreshed += 1;
            }
        }

        if npmi >= NPMI_THRESHOLD {
            continue; // still holds
        }
        if npmi >= decay_floor() {
            rep.held_band += 1; // hysteresis: questionable, not closed
            continue;
        }
        if fact::is_user_verified(conn, id)? {
            rep.held_user += 1;
            continue;
        }

        rep.eligible += 1;
        if rep.closed >= DECAY_CAP || dry_run {
            continue;
        }
        // (1) Valid-time close: true then, false now, nobody was wrong.
        fact::close_valid_time(conn, &uid, None)?;
        let payload = serde_json::json!({
            "class": "npmi", "npmi_was": stated_npmi, "npmi_now": npmi,
            "shared_was": stated_co, "shared_now": co,
        });
        crate::ledger::log_event(
            conn,
            "belief_decayed",
            Some(&uid),
            Some(&payload.to_string()),
        )?;
        rep.closed += 1;
    }
    Ok(rep)
}

// ─── Phantom repair: beliefs that were never true ────────────────────────────

#[derive(Debug, Default, Serialize)]
pub struct PhantomReport {
    pub scanned: usize,
    /// The repair set: ZERO shared episodes now — nothing supports them.
    pub zero_support: usize,
    /// Flagged by the sweep's collapse alarm but NOT repaired: a partial
    /// loss is ambiguous (a merge, a re-scope), so it stays for a human.
    pub partial_collapse: usize,
    pub held_user: usize,
    pub invalidated: usize,
    /// Distinct nodes implicated — the blast radius in people, not rows.
    pub affected_nodes: usize,
    pub samples: Vec<(String, i64)>,
}

/// Retract co-occurrence beliefs derived from mentions that no longer
/// exist at all (PLAN: a one-shot repair of a fixed producer bug, not a
/// recurring sweep).
///
/// These are **not decay**. Pre-unique-alias linking credited an
/// ambiguous first-name alias to every same-named node, NPMI computed
/// co-occurrence over the phantom mentions, and `link`'s later alias
/// rebuild correctly refused to re-link the ambiguous alias — leaving
/// beliefs with zero support. A person with one interaction cannot have
/// 297 shared episodes, so these were never true and take
/// [`fact::invalidate_never_true`], not a valid-time close.
///
/// Deliberately stricter than the alarm that found them: the sweep flags
/// at [`COLLAPSE_RATIO`], this repairs only at **zero**. Flag broadly,
/// repair narrowly. The `npmi` class is NOT demoted — the faulty
/// producer was the old alias linker, already fixed.
pub fn invalidate_phantoms(conn: &Connection, dry_run: bool) -> Result<PhantomReport> {
    let mut rep = PhantomReport::default();
    let rows: Vec<(i64, String, String, String, String)> = {
        let mut stmt = conn.prepare(
            "SELECT id, uid, subject_id, object_id, statement FROM fact
             WHERE extractor = 'npmi' AND object_id IS NOT NULL
               AND polarity = 'positive'
               AND valid_to IS NULL AND invalidated_at IS NULL",
        )?;
        let rows = stmt
            .query_map([], |r| {
                Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?))
            })?
            .collect::<std::result::Result<_, _>>()?;
        rows
    };

    let mut nodes: std::collections::HashSet<String> = Default::default();
    for (id, uid, a, b, statement) in rows {
        rep.scanned += 1;
        let stated_co = parse_cooccurrence(&statement).map(|(c, _)| c).unwrap_or(0);
        let now_co = crate::linkers::shared_episodes(conn, &a, &b)?.len() as i64;

        if now_co > 0 {
            if (now_co as f64) < (stated_co as f64) * COLLAPSE_RATIO {
                rep.partial_collapse += 1; // ambiguous — left for a human
            }
            continue;
        }
        rep.zero_support += 1;
        if fact::is_user_verified(conn, id)? {
            rep.held_user += 1;
            continue;
        }
        nodes.insert(a.clone());
        nodes.insert(b.clone());
        if rep.samples.len() < 12 {
            rep.samples
                .push((statement.chars().take(88).collect(), stated_co));
        }
        if dry_run {
            continue;
        }
        fact::invalidate_never_true(conn, &uid)?;
        let payload = serde_json::json!({
            "class": "npmi", "cause": "pre-unique-alias phantom mentions",
            "shared_claimed": stated_co, "shared_now": 0,
        });
        crate::ledger::log_event(
            conn,
            "phantom_invalidated",
            Some(&uid),
            Some(&payload.to_string()),
        )?;
        rep.invalidated += 1;
    }
    rep.affected_nodes = nodes.len();
    Ok(rep)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::open_memory;
    use crate::episode::{add_mention, upsert_episode, Episode};
    use crate::fact::{assert_fact, get_fact_by_uid, record_observation};
    use crate::graph::{upsert_node, Node};

    fn ep(conn: &Connection, sid: &str) -> i64 {
        upsert_episode(
            conn,
            &Episode {
                id: 0,
                uid: String::new(),
                source: "note".into(),
                source_id: sid.into(),
                source_ref: None,
                body: "e".into(),
                occurred_at: "2026-01-01 10:00:00".into(),
                occurred_end: None,
                ingested_at: String::new(),
                lat: None,
                lon: None,
                location: None,
                sensitivity: "personal".into(),
                scope_id: None,
                meta: None,
                raw: None,
            },
        )
        .unwrap()
        .0
    }

    /// a and b share `shared` episodes; `pad` third-party episodes keep the
    /// universe honest (padding with a member of the pair would make it a
    /// hub, which NPMI scores 0.0 by design).
    fn graph(conn: &Connection, shared: usize, b_extra: usize) {
        for (id, n) in [("a", "A"), ("b", "B"), ("pad", "Pad")] {
            upsert_node(conn, &Node::new(id, "person", n)).unwrap();
        }
        for i in 0..shared {
            let e = ep(conn, &format!("s{i}"));
            add_mention(conn, e, "a", "manual", 1.0).unwrap();
            add_mention(conn, e, "b", "manual", 1.0).unwrap();
        }
        for i in 0..12 {
            let e = ep(conn, &format!("p{i}"));
            add_mention(conn, e, "pad", "manual", 1.0).unwrap();
        }
        for i in 0..b_extra {
            let e = ep(conn, &format!("x{i}"));
            add_mention(conn, e, "b", "manual", 1.0).unwrap();
        }
    }

    fn co_fact(conn: &Connection, co: i64, npmi: f64) -> String {
        assert_fact(
            conn,
            "a",
            "related_to",
            Some("b"),
            None,
            &format!("A and B frequently co-occur ({co} shared episodes, NPMI {npmi:.2})"),
            None,
            None,
            npmi.min(0.85),
            "npmi",
        )
        .unwrap()
    }

    #[test]
    fn test_parse_and_render_roundtrip() {
        let s = "A and B frequently co-occur (5 shared episodes, NPMI 0.53)";
        assert_eq!(parse_cooccurrence(s), Some((5, 0.53)));
        let fresh = render_statement(s, 20, -0.01).unwrap();
        assert_eq!(
            fresh,
            "A and B frequently co-occur (20 shared episodes, NPMI -0.01)"
        );
        assert_eq!(parse_cooccurrence(&fresh), Some((20, -0.01)));
        assert_eq!(
            parse_cooccurrence("Ada works at Westfield"),
            None,
            "non-cooccurrence is None"
        );
    }

    #[test]
    fn test_decayed_belief_closes_valid_time_only() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 40); // b now appears everywhere ⇒ association gone
        let uid = co_fact(&conn, 3, 0.55);

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!((rep.closed, rep.eligible), (1, 1));
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        assert!(f.valid_to.is_some(), "stopped being true");
        assert!(
            f.invalidated_at.is_none(),
            "we were NOT wrong to believe it — decay is not error"
        );
        // The belief still answers for the period it held.
        assert!(!crate::fact::facts_as_of(&conn, "a", "2026-01-15", 10)
            .unwrap()
            .is_empty());
        let n: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM event_log WHERE kind = 'belief_decayed'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(n, 1);
    }

    #[test]
    fn test_hysteresis_band_holds_borderline_beliefs() {
        let conn = open_memory().unwrap();
        // Tuned so NPMI lands between the floor (0.24) and threshold
        // (0.30): for this fixture npmi = ln(N/(s+x)) / ln(N/s), so
        // s=4, x=12 gives ln(28/16)/ln(28/4) ≈ 0.288.
        graph(&conn, 4, 12);
        let uid = co_fact(&conn, 4, 0.60);
        let (npmi, _) = crate::verify::rederive_npmi(&conn, "a", "b")
            .unwrap()
            .unwrap();
        assert!(
            npmi < NPMI_THRESHOLD && npmi >= decay_floor(),
            "fixture must land inside the band, got {npmi}"
        );

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            (rep.held_band, rep.closed),
            (1, 0),
            "no flapping at the boundary"
        );
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
    }

    /// A pair that slid just under `NPMI_MIN_COOCCUR` without crossing the
    /// collapse ratio: 3 shared episodes claimed, 2 now. `rederive_npmi`
    /// answers None below the floor, and the old code read every None as an
    /// empty input set — so this decayed pair was reported to the operator as
    /// `→ 0 shared episodes: mentions lost … check the mention pipeline`,
    /// sending them to debug ingestion over a belief that had simply gone
    /// quiet. Worse, the None then fell into an `.expect("collapsed covers
    /// the None case")` that only held because the misreading swallowed it.
    ///
    /// It is ordinary decay and takes the ordinary close.
    #[test]
    fn test_below_npmi_floor_decays_rather_than_alarming() {
        let conn = open_memory().unwrap();
        graph(&conn, 2, 0); // two shared episodes; the floor is 3
        let uid = co_fact(&conn, 3, 0.55);

        let rep = sweep_npmi(&conn, false).unwrap();
        assert!(
            rep.integrity_alarms.is_empty(),
            "a pair below the floor is decay, not a pipeline alarm: {:?}",
            rep.integrity_alarms
        );
        assert_eq!(rep.closed, 1, "it should close on valid time");
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        assert!(f.valid_to.is_some(), "valid-time close");
        assert!(
            f.invalidated_at.is_none(),
            "true then, false now — never a system-time retraction"
        );
    }

    /// The same slide, on a belief the user vouched for, is held rather than
    /// closed — the new path honours the same hold as every other close.
    #[test]
    fn test_below_floor_still_respects_a_user_verified_hold() {
        let conn = open_memory().unwrap();
        graph(&conn, 2, 0);
        let uid = co_fact(&conn, 3, 0.55);
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        record_observation(&conn, f.id, None, "verified", "user", Some(1.0)).unwrap();

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!(rep.closed, 0);
        assert_eq!(rep.held_user, 1);
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
    }

    #[test]
    fn test_input_collapse_alarms_and_never_closes() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0);
        // The statement claims 297 inputs; the mention table has 3 — the
        // Ana Sorel shape (mentions destroyed by a rebuild/merge).
        let uid = co_fact(&conn, 297, 0.82);

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            rep.closed, 0,
            "a pipeline artifact must not delete a belief"
        );
        assert_eq!(rep.integrity_alarms.len(), 1);
        assert_eq!(
            rep.integrity_alarms_continuing, 0,
            "the first sighting is news"
        );
        // The detail no longer asserts a cause it cannot know. Every step
        // change in this alarm's live count landed on an operator merge,
        // split or relink, so the wording names that first.
        assert!(
            rep.integrity_alarms[0].1.contains("re-partitioned"),
            "{}",
            rep.integrity_alarms[0].1
        );
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
    }

    /// **The regression.** The alarm had no memory, so it re-narrated the
    /// identical collapse every night — 54 entries a night for eighteen
    /// days, no night distinguishable from the last. Fails on the old
    /// behaviour at the second sweep, which used to report it as news again.
    #[test]
    fn a_collapse_is_news_once_and_then_a_number() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0);
        let uid = co_fact(&conn, 297, 0.82);

        let first = sweep_npmi(&conn, false).unwrap();
        assert_eq!(first.integrity_alarms.len(), 1);
        assert_eq!(first.integrity_alarms_continuing, 0);

        // Nothing changed between the two sweeps.
        let second = sweep_npmi(&conn, false).unwrap();
        assert!(
            second.integrity_alarms.is_empty(),
            "an unchanged collapse is not a new finding: {:?}",
            second.integrity_alarms
        );
        assert_eq!(
            second.integrity_alarms_continuing, 1,
            "but it is still true, and must not read as resolved"
        );
        // And still never closed, whichever list it lands in.
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
    }

    /// **Review finding, and the worst kind: the preview consumed the
    /// news.** Every other write in `sweep_npmi` is gated on `dry_run`; the
    /// alarm upsert was not. So `decay --dry-run` — which prints "(dry run
    /// — nothing changed)" — recorded the collapses it had just shown, and
    /// the real run afterwards reported `new=0`, downgrading a first
    /// sighting to a silent "continuing" number no later run would raise.
    ///
    /// Fails on the code as reviewed at the final assertion.
    #[test]
    fn a_dry_run_does_not_consume_the_news() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0);
        co_fact(&conn, 297, 0.82);

        let preview = sweep_npmi(&conn, true).unwrap();
        assert_eq!(
            preview.integrity_alarms.len(),
            1,
            "the preview still reports"
        );

        let rows: i64 = conn
            .query_row("SELECT COUNT(*) FROM cooccurrence_alarm", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 0, "a dry run must write nothing");

        // And the real sweep that follows still has news to report.
        let real = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            real.integrity_alarms.len(),
            1,
            "the preview must not have consumed the first sighting"
        );
        assert_eq!(real.integrity_alarms_continuing, 0);
    }

    /// **Review finding.** `news` compared the remembered observation and
    /// ignored the remembered baseline, so a belief that collapsed,
    /// recovered, was re-rendered against a higher stated count, then
    /// collapsed again from it was reported as "continuing": remembered 3,
    /// restated to 100, today 20 — an 80-episode loss silenced because
    /// `20 < 3` is false. A moved baseline makes the remembered observation
    /// incomparable, so it is news.
    #[test]
    fn a_moved_baseline_makes_the_old_observation_incomparable() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0);
        let uid = co_fact(&conn, 297, 0.82);
        assert_eq!(sweep_npmi(&conn, false).unwrap().integrity_alarms.len(), 1);
        assert!(sweep_npmi(&conn, false)
            .unwrap()
            .integrity_alarms
            .is_empty());

        // The remembered row now claims a much smaller baseline than the
        // statement does — the shape a refresh-then-recollapse leaves.
        conn.execute(
            "UPDATE cooccurrence_alarm SET stated_co = 4, observed_co = 1 WHERE fact_uid = ?1",
            rusqlite::params![uid],
        )
        .unwrap();
        let after = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            after.integrity_alarms.len(),
            1,
            "the baseline moved, so the remembered observation cannot silence this"
        );
    }

    /// A collapse that DEEPENS is news again — the suppression must not
    /// swallow a situation getting worse, which is the failure mode of
    /// every "only tell me once" rule.
    #[test]
    fn a_worsening_collapse_speaks_up_again() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0);
        co_fact(&conn, 297, 0.82);
        assert_eq!(sweep_npmi(&conn, false).unwrap().integrity_alarms.len(), 1);
        assert!(sweep_npmi(&conn, false)
            .unwrap()
            .integrity_alarms
            .is_empty());

        // Two of the three remaining shared episodes go away.
        conn.execute(
            "DELETE FROM mention WHERE episode_id IN (SELECT id FROM episode LIMIT 2)",
            [],
        )
        .unwrap();
        let worse = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            worse.integrity_alarms.len(),
            1,
            "a deeper collapse is a new finding"
        );
        assert!(
            worse.integrity_alarms[0].1.contains("when first reported"),
            "{}",
            worse.integrity_alarms[0].1
        );
    }

    #[test]
    fn test_user_verified_belief_survives_recomputation() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 40);
        let uid = co_fact(&conn, 3, 0.55);
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        record_observation(&conn, f.id, None, "verified", "user", Some(1.0)).unwrap();

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!(
            (rep.held_user, rep.closed),
            (1, 0),
            "a person outranks a recomputation"
        );
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
    }

    #[test]
    fn test_drifted_statement_is_refreshed_and_requeued_for_embedding() {
        let conn = open_memory().unwrap();
        graph(&conn, 5, 0); // still well above threshold
        let uid = co_fact(&conn, 3, 0.31); // stale numbers in the text
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        conn.execute(
            "INSERT INTO vec_fact (fact_id, embedding) VALUES (?1, ?2)",
            params![f.id, serde_json::to_string(&vec![0.1f32; 768]).unwrap()],
        )
        .unwrap();

        let rep = sweep_npmi(&conn, false).unwrap();
        assert_eq!((rep.refreshed, rep.closed), (1, 0));
        let after = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        assert_eq!(
            parse_cooccurrence(&after.statement).unwrap().0,
            5,
            "the statement no longer asserts arithmetic the graph disbelieves"
        );
        let vecs: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM vec_fact WHERE fact_id = ?1",
                params![f.id],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(vecs, 0, "stale vector dropped so the nightly re-embeds");
    }

    #[test]
    fn test_phantom_invalidation_is_never_true_not_decay() {
        let conn = open_memory().unwrap();
        graph(&conn, 0, 0); // nodes and padding exist; a and b share NOTHING
        let uid = co_fact(&conn, 297, 0.82); // the Ana call shape

        let dry = invalidate_phantoms(&conn, true).unwrap();
        assert_eq!((dry.zero_support, dry.invalidated), (1, 0));
        assert_eq!(dry.affected_nodes, 2);
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .invalidated_at
            .is_none());

        let rep = invalidate_phantoms(&conn, false).unwrap();
        assert_eq!(rep.invalidated, 1);
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        assert!(
            f.invalidated_at.is_some(),
            "we were wrong — system time closes"
        );
        // Zero-length valid window: an as-of query must never serve it,
        // unlike a decayed belief which stays true for its period.
        assert_eq!(f.valid_to, f.valid_from, "zero-length validity window");
        assert!(
            f.valid_from.is_some(),
            "both endpoints pinned, not just valid_to"
        );
        for date in ["2016-01-01", "2026-01-01", "2030-01-01"] {
            assert!(
                crate::fact::facts_as_of(&conn, "a", date, 10)
                    .unwrap()
                    .is_empty(),
                "a belief that was never true answers no as-of date ({date})"
            );
        }
        // The history of having believed it survives.
        assert!(!crate::fact::timeline(&conn, "a", None, None)
            .unwrap()
            .is_empty());
    }

    #[test]
    fn test_partial_collapse_is_not_repaired() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 0); // 3 shared now
        co_fact(&conn, 26, 0.53); // claimed 26 — a partial loss, ambiguous

        let rep = invalidate_phantoms(&conn, false).unwrap();
        assert_eq!((rep.zero_support, rep.invalidated), (0, 0));
        assert_eq!(
            rep.partial_collapse, 1,
            "flag broadly, repair narrowly — only zero support is unambiguous"
        );
    }

    #[test]
    fn test_user_verified_phantom_is_held() {
        let conn = open_memory().unwrap();
        graph(&conn, 0, 0);
        let uid = co_fact(&conn, 297, 0.82);
        let f = get_fact_by_uid(&conn, &uid).unwrap().unwrap();
        record_observation(&conn, f.id, None, "verified", "user", Some(1.0)).unwrap();

        let rep = invalidate_phantoms(&conn, false).unwrap();
        assert_eq!((rep.held_user, rep.invalidated), (1, 0));
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .invalidated_at
            .is_none());
    }

    #[test]
    fn test_dry_run_changes_nothing_but_still_counts() {
        let conn = open_memory().unwrap();
        graph(&conn, 3, 40);
        let uid = co_fact(&conn, 3, 0.55);
        let rep = sweep_npmi(&conn, true).unwrap();
        assert_eq!((rep.eligible, rep.closed), (1, 0));
        assert!(rep.refreshed >= 1, "drift is reported in a dry run too");
        assert!(get_fact_by_uid(&conn, &uid)
            .unwrap()
            .unwrap()
            .valid_to
            .is_none());
        assert_eq!(
            parse_cooccurrence(&get_fact_by_uid(&conn, &uid).unwrap().unwrap().statement).unwrap(),
            (3, 0.55),
            "statement untouched in a dry run"
        );
    }
}
